name: todo_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  # async: # This was here, is it needed? I'll keep it for now.
  sqflite: ^2.4.2
  path_provider:
  http: ^1.5.0
  intl: ^0.19.0 # Added intl

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
